import { PresetTemplate } from '../types';

export const PRESET_TEMPLATES: PresetTemplate[] = [
  {
    id: 'classic-pro',
    name: 'Classic Minimal',
    description: 'Clean high-contrast black and crisp white layout',
    previewGradient: 'from-gray-900 to-black',
    config: {
      moduleStyle: 'square',
      colors: {
        fgType: 'none',
        fgColor: '#000000',
        fgGradientEnd: '#000000',
        fgGradientAngle: 45,
        bgType: 'none',
        bgColor: '#ffffff',
        bgGradientEnd: '#ffffff',
        bgGradientAngle: 45,
        transparentBg: false,
        customEyeColors: false,
        eyeOuterColor: '#000000',
        eyeInnerColor: '#000000',
      },
      eyes: {
        outerStyle: 'square',
        innerStyle: 'square',
      },
      frame: {
        style: 'none',
        text: 'SCAN ME',
        textColor: '#ffffff',
        bgColor: '#000000',
        borderColor: '#000000',
        borderWidth: 0,
        fontSize: 14,
        fontFamily: 'sans-serif',
      },
    },
  },
  {
    id: 'cyberpunk-neon',
    name: 'Cyberpunk Neon',
    description: 'Vibrant neon cyan & magenta gradient on pitch dark background',
    previewGradient: 'from-cyan-500 via-purple-500 to-fuchsia-500',
    config: {
      moduleStyle: 'fluid',
      colors: {
        fgType: 'linear',
        fgColor: '#00f2fe',
        fgGradientEnd: '#4facfe',
        fgGradientAngle: 135,
        bgType: 'none',
        bgColor: '#0f172a',
        bgGradientEnd: '#0f172a',
        bgGradientAngle: 0,
        transparentBg: false,
        customEyeColors: true,
        eyeOuterColor: '#ff007f',
        eyeInnerColor: '#00f2fe',
      },
      eyes: {
        outerStyle: 'hexagon',
        innerStyle: 'star',
      },
      frame: {
        style: 'neon-glow',
        text: '⚡ SCAN HERE',
        textColor: '#00f2fe',
        bgColor: '#0f172a',
        borderColor: '#ff007f',
        borderWidth: 2,
        fontSize: 14,
        fontFamily: 'monospace',
      },
    },
  },
  {
    id: 'sunset-luxe',
    name: 'Sunset Luxe',
    description: 'Warm glowing gradient with elegant diamond finder eyes',
    previewGradient: 'from-rose-500 via-amber-500 to-yellow-400',
    config: {
      moduleStyle: 'rounded',
      colors: {
        fgType: 'linear',
        fgColor: '#f43f5e',
        fgGradientEnd: '#f59e0b',
        fgGradientAngle: 45,
        bgType: 'none',
        bgColor: '#fff1f2',
        bgGradientEnd: '#fff1f2',
        bgGradientAngle: 0,
        transparentBg: false,
        customEyeColors: true,
        eyeOuterColor: '#be123c',
        eyeInnerColor: '#d97706',
      },
      eyes: {
        outerStyle: 'leaf',
        innerStyle: 'diamond',
      },
      frame: {
        style: 'bottom-badge',
        text: '✨ DISCOVER MORE',
        textColor: '#ffffff',
        bgColor: '#be123c',
        borderColor: '#be123c',
        borderWidth: 0,
        fontSize: 13,
        fontFamily: 'sans-serif',
      },
    },
  },
  {
    id: 'emerald-eco',
    name: 'Emerald Eco',
    description: 'Deep forest greens with smooth organic leaf eyes',
    previewGradient: 'from-emerald-600 to-teal-500',
    config: {
      moduleStyle: 'dots',
      colors: {
        fgType: 'linear',
        fgColor: '#059669',
        fgGradientEnd: '#0d9488',
        fgGradientAngle: 90,
        bgType: 'none',
        bgColor: '#f0fdf4',
        bgGradientEnd: '#f0fdf4',
        bgGradientAngle: 0,
        transparentBg: false,
        customEyeColors: true,
        eyeOuterColor: '#047857',
        eyeInnerColor: '#115e59',
      },
      eyes: {
        outerStyle: 'leaf',
        innerStyle: 'dot',
      },
      frame: {
        style: 'floating-tag',
        text: '🌿 SUSTAINABLE BRAND',
        textColor: '#047857',
        bgColor: '#dcfce7',
        borderColor: '#059669',
        borderWidth: 1.5,
        fontSize: 12,
        fontFamily: 'sans-serif',
      },
    },
  },
  {
    id: 'coffee-wifi',
    name: 'Coffee Wi-Fi',
    description: 'Warm coffee shop aesthetic for instant guest Wi-Fi connection',
    previewGradient: 'from-amber-800 to-amber-950',
    config: {
      moduleStyle: 'classy',
      colors: {
        fgType: 'none',
        fgColor: '#451a03',
        fgGradientEnd: '#451a03',
        fgGradientAngle: 0,
        bgType: 'none',
        bgColor: '#fef3c7',
        bgGradientEnd: '#fef3c7',
        bgGradientAngle: 0,
        transparentBg: false,
        customEyeColors: true,
        eyeOuterColor: '#78350f',
        eyeInnerColor: '#b45309',
      },
      eyes: {
        outerStyle: 'rounded',
        innerStyle: 'dot',
      },
      frame: {
        style: 'top-banner',
        text: '☕ FREE GUEST WI-FI',
        textColor: '#ffffff',
        bgColor: '#78350f',
        borderColor: '#78350f',
        borderWidth: 0,
        fontSize: 14,
        fontFamily: 'serif',
      },
    },
  },
  {
    id: 'royal-gold',
    name: 'Royal Gold',
    description: 'Opulent metallic gold gradient with high-end luxury frame',
    previewGradient: 'from-yellow-600 via-amber-400 to-yellow-600',
    config: {
      moduleStyle: 'stars',
      colors: {
        fgType: 'linear',
        fgColor: '#b45309',
        fgGradientEnd: '#f59e0b',
        fgGradientAngle: 120,
        bgType: 'none',
        bgColor: '#18181b',
        bgGradientEnd: '#18181b',
        bgGradientAngle: 0,
        transparentBg: false,
        customEyeColors: true,
        eyeOuterColor: '#f59e0b',
        eyeInnerColor: '#fbbf24',
      },
      eyes: {
        outerStyle: 'double',
        innerStyle: 'star',
      },
      frame: {
        style: 'polaroid',
        text: '👑 VIP PASS',
        textColor: '#f59e0b',
        bgColor: '#09090b',
        borderColor: '#f59e0b',
        borderWidth: 2,
        fontSize: 14,
        fontFamily: 'serif',
      },
    },
  },
  {
    id: 'pastel-social',
    name: 'Pastel Social',
    description: 'Soft lavender and purple aesthetic perfect for Instagram & TikTok link trees',
    previewGradient: 'from-indigo-400 via-purple-400 to-pink-400',
    config: {
      moduleStyle: 'dots',
      colors: {
        fgType: 'linear',
        fgColor: '#7c3aed',
        fgGradientEnd: '#db2777',
        fgGradientAngle: 45,
        bgType: 'none',
        bgColor: '#faf5ff',
        bgGradientEnd: '#faf5ff',
        bgGradientAngle: 0,
        transparentBg: false,
        customEyeColors: true,
        eyeOuterColor: '#6d28d9',
        eyeInnerColor: '#be185d',
      },
      eyes: {
        outerStyle: 'circle',
        innerStyle: 'heart',
      },
      frame: {
        style: 'bottom-badge',
        text: '💖 SCAN FOR SOCIALS',
        textColor: '#ffffff',
        bgColor: '#7c3aed',
        borderColor: '#7c3aed',
        borderWidth: 0,
        fontSize: 13,
        fontFamily: 'sans-serif',
      },
    },
  },
];
